#!/bin/bash
cat scan.txt | ./example lfu 50
cat scan.txt | ./example lfu 100
cat scan.txt | ./example lfu 150
cat scan.txt | ./example lfu 200
cat scan.txt | ./example lfu 250
cat scan.txt | ./example lfu 300
cat scan.txt | ./example lfu 350
cat scan.txt | ./example lfu 400
cat scan.txt | ./example lfu 450
cat scan.txt | ./example lfu 500
cat scan.txt | ./example lfu 550
cat scan.txt | ./example lfu 600
cat scan.txt | ./example lru 50
cat scan.txt | ./example lru 100
cat scan.txt | ./example lru 150
cat scan.txt | ./example lru 200
cat scan.txt | ./example lru 250
cat scan.txt | ./example lru 300
cat scan.txt | ./example lru 350
cat scan.txt | ./example lru 400
cat scan.txt | ./example lru 450
cat scan.txt | ./example lru 500
cat scan.txt | ./example lru 550
cat scan.txt | ./example lru 600
cat scan.txt | ./example fifo 50
cat scan.txt | ./example fifo 100
cat scan.txt | ./example fifo 150
cat scan.txt | ./example fifo 200
cat scan.txt | ./example fifo 250
cat scan.txt | ./example fifo 300
cat scan.txt | ./example fifo 350
cat scan.txt | ./example fifo 400
cat scan.txt | ./example fifo 450
cat scan.txt | ./example fifo 500
cat scan.txt | ./example fifo 550
cat scan.txt | ./example fifo 600
cat scan.txt | ./example random 50
cat scan.txt | ./example random 100
cat scan.txt | ./example random 150
cat scan.txt | ./example random 200
cat scan.txt | ./example random 250
cat scan.txt | ./example random 300
cat scan.txt | ./example random 350
cat scan.txt | ./example random 400
cat scan.txt | ./example random 450
cat scan.txt | ./example random 500
cat scan.txt | ./example random 550
cat scan.txt | ./example random 600
